#!/bin/sh

### BEGIN INIT INFO
# Provides: nxpush
# Required-Start: 
# Required-Stop: 
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: nxpush initialization
# Description: nxpush init script
### END INIT INFO

NXPUSH_HOME=/home/nxpush/nxpush
PID_FILE=/home/nxpush/nxpush.pid
PYTHON=/usr/bin/python
DAEMON=$NXPUSH_HOME/nxpush.py
DAEMON_USER=nxpush
START_STOP_DAEMON=/sbin/start-stop-daemon

#. /lib/lsb/init-functions

case "$1" in
        start)
		       	$START_STOP_DAEMON --start --background --pidfile $PID_FILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --exec $PYTHON $DAEMON

                        
                ;;
        stop)
                        $START_STOP_DAEMON --stop --pidfile $PID_FILE
                	if [ -f $PID_FILE ]
			then
				rm $PID_FILE
			fi         
			exit 0
                ;;
        *)
                        echo "Usage: nxpush {start|stop}"
                        exit 1
esac

